# Review and Gerrit configuration

# Lustre project directory
lustre_dir: "/Users/mvef/git_wip/lustre-release"

# Default instruction file
default_instruction_file: "config/default_instruction.txt"

# Common AI references to add to the context
common_ai_refs:
  - "/Users/mvef/PycharmProjects/Aider_hackathon/ai_reference/lustre_arch.md"

# API keys
api_keys:
  free_gemini: "AIzaSyCmFZ5jYbIKYwtdfynby_WaGD7FDouyqvc"
  paid_gemini: "AIzaSyDwPO_2pjenfvJXLH29-1XkrWjOLanV52I"

# Model settings
models:
  free_model: "gemini/gemini-2.5-pro-exp-03-25"
  paid_model: "gemini/gemini-2.5-pro-preview-03-25"

# Model metadata file path
model_metadata_file: "config/model-metadata.json"

# Token limits
max_tokens: 200000
map_tokens: 8192

# Directories to ignore when adding files to context
ignored_dirs:
  - "lustre/tests"

# Gerrit server settings
gerrit:
  # Gerrit server URL
  url: "https://review.whamcloud.com"

  # Project name
  project: "fs/lustre-release"

  # Branch name
  branch: "master"

  # Authentication settings
  auth:
    username: "mvef"
    password: "fYWCNvCHgYIOw4Vzy70/hK8R6myWIUGoif/3enkIOQ"
